language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $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
 local_dir: dist
 on:
   branch: main