language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $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
 local_dir: dist
 on:
   branch: main